### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by tunikakeks** [yesdog/Waterdog#67] opened 2019-11-01 00:04 UTC
**Version of Waterdog**

**Expected Behavior**

**Actual Behavior**

**Crashdump, Backtrace or Other Files**

**Describe the bug**

**To Reproduce**

**Screenshots**

**Server software used:**

**Additional context**

Please Update to mcbe / mcpe 1.13.x and also update the latest .jar file. Thanks!

**Comment by colinrgodsey** [comment] 2019-11-09 16:21
Update coming soon. Watch the discord for more details

**Comment by colinrgodsey** [comment] 2019-11-09 16:24
duplicate of #68

**Closed by colinrgodsey** 2019-11-09 16:24 UTC
Labels: duplicate
