### ISSUE TITLE
Players are disappearing 

### ISSUE THREAD

**Issue by LelouBil** [yesdog/Waterdog#88] opened 2020-01-20 21:34 UTC
Players are sometime dissapearing using git:Waterdog-Bootstrap:1.15-SNAPSHOT:81eb6a5:300 and the official server software. It could be a duplicate of #51

**Comment by Wertzui123** [comment] 2020-01-22 06:26
Yea, I think it's the same bug as #51

**Comment by TobiasG-DE** [comment] 2020-01-22 06:43
That's a weird issue. Are there any patterns with the players disappearing and is there any way to reproduce it, f.e. is it happening when transferring to another Server?

Regards,
TobiasDev

**Comment by TobiasG-DE** [comment] 2020-01-22 06:50
Btw reading #51, this should be an Issue with BDS only, what is confusing, but might be worth looking into.

**Comment by Alemiz112** [comment] 2021-01-27 15:21
I believe this is already fixed as we havent heard anything similar since this issue. You can reopen issue if needed.

**Closed by Alemiz112** 2021-01-27 15:21 UTC
Labels: bug, low-prio, vanilla
