### ISSUE TITLE
Scoreboard flickers when you update it

### ISSUE THREAD

**Issue by LucGamesYT** [yesdog/Waterdog#141] opened 2020-07-24 08:02 UTC
**Version of Waterdog**
 git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4

**Expected Behavior**
No flickers

**Actual Behavior**
Scoreboard flickers when you update it

**To Reproduce**
1. Create a scoreboard
2. Update the scoreboard (PlayerMoveEvent)

**Screenshots**
https://youtu.be/-4BwEnOkpYI

**Server software used:**
Nukkit

**Comment by Alemiz112** [comment] 2020-07-24 08:51
Duplicate of #62. Closing.

**Closed by Alemiz112** 2020-07-24 08:51 UTC
Labels: bug, needs-verify

**Comment by LucGamesYT** [comment] 2020-07-24 08:53
> Duplicate of #62. Closing.

Yeah, I know. Unfortunately, the bug's been in there for almost a year.

**Comment by Alemiz112** [comment] 2020-07-24 08:56
There are more bugs that can not be solved for some reasons. Opening new issue wont make it fixed.
