### ISSUE TITLE
I cant join MCPE  version 1.16.100 based pocketmine server with WaterDog Proxy Pls Help

### ISSUE THREAD

**Issue by XxTOUHIDxX** [yesdog/Waterdog#167] opened 2020-11-23 17:04 UTC

**Comment by Guillaume351** [comment] 2020-11-23 17:11
Hello, the update is being worked on and according to what I saw on the Discord server we can expect it this week. This is a duplicate of the issue #165

**Comment by XxTOUHIDxX** [comment] 2020-11-23 18:37
Owww Ok I amma wait for the update

**Closed** 2020-11-23 19:38 UTC
