### ISSUE TITLE
block palette bug

### ISSUE THREAD

**Issue by EinBexiii** [yesdog/Waterdog#70] opened 2019-11-22 13:27 UTC
Version of Waterdog
latest

Expected Behavior
nothing

Actual Behavior
When you click on a block, other blocks spawn.

Describe the bug
When you click on a block, other blocks spawn.

To Reproduce
Right click on a block

Screenshots

Server software used:
Nukkit

**Comment by colinrgodsey** [comment] 2019-11-22 13:53
can't reproduce using the bedrock-1.13 branch of nukkit. what branch are you using for 1.13?

**Comment by Alemiz112** [comment] 2019-11-22 13:57
I can confirm that. Probably is caused by different block pallets between servers. There are lot of own forks for 1.13 servers. This forks can have different block pallete than WaterDog.

**Comment by Wertzui123** [comment] 2019-12-11 21:12
Happens to me at PocketMine 3.11.1 too

**Comment by FlussRaplay** [comment] 2019-12-12 08:29
The Bug is fixed by KCodeYT

**Comment by GamakCZ** [comment] 2019-12-14 10:56
It works when player connect to the first server, but after transfer it's bugged

**Comment by colinrgodsey** [comment] 2019-12-14 18:41
fixed in https://github.com/yesdog/Waterdog/commit/403f2f7d76c6569322a9f678b926a51853f56dee

**Closed by colinrgodsey** 2019-12-14 18:41 UTC
Labels: bug
