### ISSUE TITLE
Cancelling the LoginEvent causes issues on MCPE

### ISSUE THREAD

**Issue by juliarn** [yesdog/Waterdog#59] opened 2019-09-06 20:43 UTC
**Version of Waterdog**
git:Waterdog-Bootstrap:1.14-SNAPSHOT:85410b6:278

**Expected Behavior**
Normally, you would just be kicked with the set cancel-reason.

**Actual Behavior**
The "Disconnected from server" screen is shown for a short moment, you don't see the cancel-reason. Then, you get stuck in the "loading-resources-screen" (I attached a screenshot below). To be able to play again, you have to restart MCPE.

**To Reproduce**
Just cancel the login-event, set a cancel reason and try to join.

**Screenshots**
![Screenshot_20190906-223921_Minecraft](https://user-images.githubusercontent.com/42209193/64459105-69adad00-d0f7-11e9-8677-a068132a5a10.jpg)

**Server software used:**
Nukkit

**Comment by EOT3000** [comment] 2019-09-07 15:55
I can confirm this. I have worked with the bedrock protocol, and this has happened before. Can be mismatched protocol version????

**Comment by Xernium** [comment] 2019-09-20 23:17
This is unlikely to be caused by version mismatch. This loop happens when the connection is closed and the correct abort packet never gets to the client. I still have no idea why the connection closes before that is sent (or its sent incorrectly) but this does happen. I need to look into this more

**Comment by lukeeey** [comment] 2019-10-04 13:38
Client bug

**Comment by Alemiz112** [comment] 2020-06-07 12:30
Closing as no new activity here. Also I have not noticed this since 1.13.

**Closed by Alemiz112** 2020-06-07 12:30 UTC
Labels: bug

**Comment by Wertzui123** [comment] 2021-05-17 15:39
So, I've noticed when cancelling the login event on a pocketmine server, it normally shows the correct message but only enters this weird bug state when using Waterdog.
This means this is still an issue and seems to be caused by the proxy, not directly by the client.

**Comment by Wertzui123** [comment] 2021-05-17 15:45
Looks like it doesn't work on normal pocketmine either, just cancelling the PreLoginEvent does, but still not on Waterdog.
