### ISSUE TITLE
Issues and more issues

### ISSUE THREAD

**Issue by NycuRO** [yesdog/Waterdog#4] opened 2019-04-25 17:12 UTC
Actually if you use nukkit, hologram don't have tag 'alwaysVisible'

AND

```Server.getInstance().dispatchCommand(player, "command");```

not works well.
![image](https://user-images.githubusercontent.com/13573011/56754691-52000880-6796-11e9-98ea-44eacd5f20e4.png)

Actually, you can see, if you use command who exist on dispatching, server says not exists.
If you use yourself, seems to work.

**Comment by NycuRO** [comment] 2019-04-25 17:12
About Holograms:


![image](https://user-images.githubusercontent.com/13573011/56754774-8247a700-6796-11e9-9555-18bab1175230.png)

**Comment by NycuRO** [comment] 2019-04-25 17:16
I've found a bug who spam my console.

If i add offline server to listeners and after turn them on, is this:

![image](https://user-images.githubusercontent.com/13573011/56754944-f1bd9680-6796-11e9-96f7-94083e3f3ded.png)

**Comment by NycuRO** [comment] 2019-04-25 17:21
Another bug:

![image](https://user-images.githubusercontent.com/13573011/56755205-a35cc780-6797-11e9-8d32-8491ea3229d0.png)



If you are on lobby and someone enter, and after you go to factions *another proxy server*, player list is not reseted

**Comment by NycuRO** [comment] 2019-04-25 17:22
Another bug:

![image](https://user-images.githubusercontent.com/13573011/56755255-c0919600-6797-11e9-8768-750d98b1f46c.png)



If you are on hub server and have 20/20 food level and you go to factions where you have 10/20 food level, client force to have food you have on hub (20/20) and you can get hurt by server having 20/20 level food :d

**Comment by NycuRO** [comment] 2019-04-25 17:24
Another bug:

![image](https://user-images.githubusercontent.com/13573011/56755376-1108f380-6798-11e9-8d50-8195d710d1ad.png)

ScoreboardPacket is not reseting on transfer.

**Comment by colinrgodsey** [comment] 2019-04-25 21:34
Scoreboard fixed in https://github.com/yesdog/Waterdog/commit/7e05b95c4d1754a08a07384a8b1a2ddd4515e1b1

Dispatch command wont work the way you're trying. it needs to use the CustomMessage packet (0x75) using the standard Bungeecord registered message keys.

We don't manipulate entity metadata in a way that could issues with holograms, so not sure what the problem is there.

**Closed by colinrgodsey** 2019-04-25 21:34 UTC

**Comment by NycuRO** [comment] 2019-04-25 21:38
What about food problem? @colinrgodsey
