### ISSUE TITLE
1.13 Update not yet stable

### ISSUE THREAD

**Issue by LymmyHD** [yesdog/Waterdog#69] opened 2019-11-09 16:22 UTC
[16:20:34] [Netty Worker IO Thread #4/INFO]: [LymmyHD|/95.222.25.33:6807] <-> ServerConnector [lobby-1] has connected
[16:20:34] [Netty Worker IO Thread #4/ERROR]: [/95.222.25.33:6807|LymmyHD] <-> DownstreamBridge <-> [lobby-1] - encountered exception
java.lang.IndexOutOfBoundsException: length(536870911) exceeds src.readableBytes(224673) where src is: PooledUnsafeDirectByteBuf(ridx: 51, widx: 224724, cap: 224740)
	at io.netty.buffer.AbstractByteBuf.checkReadableBounds(AbstractByteBuf.java:633) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1087) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at net.md_5.bungee.entitymap.EntityMap_PE.lambda$static$2(EntityMap_PE.java:265) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at net.md_5.bungee.entitymap.EntityMap_PE.lambda$doRewrite$0(EntityMap_PE.java:37) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at net.md_5.bungee.entitymap.EntityMap_PE.doRewrite(EntityMap_PE.java:112) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at net.md_5.bungee.entitymap.EntityMap_PE.rewriteClientbound(EntityMap_PE.java:27) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:110) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:139) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:112) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at network.ycc.raknet.pipeline.DisconnectHandler.channelRead(DisconnectHandler.java:27) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at network.ycc.raknet.packet.FrameSet.lambda$createFrames$5(FrameSet.java:166) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
	at network.ycc.raknet.packet.FrameSet.createFrames(FrameSet.java:166) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at network.ycc.raknet.pipeline.ReliabilityHandler.readFrameSet(ReliabilityHandler.java:138) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at network.ycc.raknet.pipeline.ReliabilityHandler.channelRead(ReliabilityHandler.java:101) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at network.ycc.raknet.client.channel.RakNetClientChannel$ClientHandler.channelRead(RakNetClientChannel.java:108) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:154) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at network.ycc.raknet.channel.DatagramChannelProxy$ListenerInboundProxy.channelRead(DatagramChannelProxy.java:371) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:513) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:382) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:bcab14a:283]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[16:20:34] [Netty Worker IO Thread #4/INFO]: [LymmyHD] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by colinrgodsey** [comment] 2019-11-09 16:24
duplicate of #68. we'll track progress there, add more details if you can. also, please use the template in the future so we can see what build number any of this is

**Closed by colinrgodsey** 2019-11-09 16:24 UTC
Labels: bug, needs-verify
